-- Create resources table
CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    folder TEXT DEFAULT 'General',
    subject TEXT DEFAULT 'N/A',
    type TEXT,
    size TEXT,
    file_data TEXT NOT NULL, -- Base64 encoded file
    uploader_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    uploader_name TEXT,
    uploader_role TEXT,
    date TEXT -- YYYY-MM-DD format as used in frontend
);

-- Enable RLS
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Create policies
-- 1. Everyone authenticated can view resources
CREATE POLICY "Allow authenticated view" ON public.resources
    FOR SELECT USING (auth.role() = 'authenticated');

-- 2. Everyone authenticated can upload
CREATE POLICY "Allow authenticated insert" ON public.resources
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 3. Only owner or admin can delete
CREATE POLICY "Allow owner or admin delete" ON public.resources
    FOR DELETE USING (
        auth.uid() = uploader_id OR 
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );
