-- Create tables for Study Groups functionality

-- 1. Study Groups
CREATE TABLE IF NOT EXISTS public.study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    description TEXT,
    subject TEXT,
    type TEXT DEFAULT 'public', -- 'public' or 'private'
    created_by UUID REFERENCES public.users(id) ON DELETE SET NULL, 
    code TEXT UNIQUE
);

-- 2. Group Members (Who is in which group)
CREATE TABLE IF NOT EXISTS public.group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    group_id BIGINT REFERENCES public.study_groups(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'member', -- 'admin' or 'member'
    UNIQUE(group_id, user_id)
);

-- 3. Group Messages (Chat history)
CREATE TABLE IF NOT EXISTS public.group_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    group_id BIGINT REFERENCES public.study_groups(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    user_name TEXT, -- Cache sender name for quicker display
    content TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE public.study_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_messages ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Study Groups: Everyone can view public groups
CREATE POLICY "Public groups are viewable by everyone" ON public.study_groups
    FOR SELECT USING (true);

-- Authenticated users can create groups
CREATE POLICY "Authenticated users can create groups" ON public.study_groups
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Only group creator or admin can delete
CREATE POLICY "Creator or Admin can delete groups" ON public.study_groups
    FOR DELETE USING (
        auth.uid() = created_by OR 
        EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );


-- Group Members: Everyone can see who is in a group (for now, simplistic)
CREATE POLICY "View group members" ON public.group_members
    FOR SELECT USING (true);

-- Authenticated users can join groups
CREATE POLICY "Join groups" ON public.group_members
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Members can leave
CREATE POLICY "Leave groups" ON public.group_members
    FOR DELETE USING (auth.uid() = user_id);


-- Group Messages: Only members can view messages
CREATE POLICY "View messages if member" ON public.group_messages
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.group_members 
            WHERE group_id = public.group_messages.group_id 
            AND user_id = auth.uid()
        )
    );

-- Only members can send messages
CREATE POLICY "Send messages if member" ON public.group_messages
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.group_members 
            WHERE group_id = public.group_messages.group_id 
            AND user_id = auth.uid()
        )
    );
